/** 制作影集业务常量 */

const ALBUM_ENTRY_MIN_TOTAL = 40
const ALBUM_SELECT_MIN = 30
const ALBUM_SELECT_MAX = 40
const ALBUM_POINTS_PER_PHOTO = 23
const ALBUM_PHOTO_PAGE_SIZE = 40

module.exports = {
  ALBUM_ENTRY_MIN_TOTAL,
  ALBUM_SELECT_MIN,
  ALBUM_SELECT_MAX,
  ALBUM_POINTS_PER_PHOTO,
  ALBUM_PHOTO_PAGE_SIZE
}
